### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by ceiron61** [vsbuffalo/scythe#26]
Hi Vince,

Does Scythe support gzipped input and ouput fastq files? I can't see anything regarding compressed files in the docs. Can you please clarify what's the best way to deal with compressed files?

My guess is that it accepts gzipped input but generates uncompressed output, is that right?

Thanks!

**Comment by vsbuffalo** [comment]
Scythe does support gzipped input files. For output files, I would recommend piping to gzip or using process substitution (e.g. http://vincebuffalo.com/2013/08/08/the-mighty-named-pipe.html)
