### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by slengyel** [vsbuffalo/scythe#28]
I get the following error when trying to build and install scythe (GCC and zlib is installed):

$ make build
gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99 -lz -lm match.o scythe.o util.o prob.o -o scythe
scythe.o: In function `ks_getc':
scythe.c:(.text+0x18c): undefined reference to`gzread'
scythe.o: In function `ks_getuntil':
scythe.c:(.text+0x284): undefined reference to`gzread'
scythe.o: In function `main':
scythe.c:(.text+0xc54): undefined reference to`gzopen'
scythe.c:(.text+0xfaf): undefined reference to `gzclose'
scythe.c:(.text+0xfd6): undefined reference to`gzopen'
scythe.c:(.text+0x1490): undefined reference to `gzclose'
util.o: In function`ks_getc':
util.c:(.text+0x18c): undefined reference to `gzread'
util.o: In function`ks_getuntil':
util.c:(.text+0x284): undefined reference to `gzread'
prob.o: In function`qual_to_probs':
prob.c:(.text+0x115): undefined reference to `powf'
prob.c:(.text+0x183): undefined reference to`powf'
collect2: error: ld returned 1 exit status
make: **\* [build] Error 1

Thanks!

**Comment by vsbuffalo** [comment]
Thanks for using Scythe (well, trying to at least). Is this the newest Github version? I would try "make all"; I think what's happening here is that somehow the linking flags -lz and -lm are coming before your compile steps in the GCC command. I thought this issue was fixed. If make all does not work, can you try:

```
$ gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99  match.o scythe.o util.o prob.o -o scythe -lz -lm
```

(I've emailed you these same comments; posting here for record).

**Comment by slengyel** [comment]
When I run 'make all' (I tried that too earlier. There are two conflicting install/build directions. The readme that comes with scythe says to do 'make build' the readme on gihub says 'make all'.

Here's the error with 'make all':

"""make: **\* No rule to make target 'all'. Stop."""

However, running the command outside the make file that you provided, does create an executable. I do get the help/usage screen when running './scythe'

Thanks for your help!

**Comment by vsbuffalo** [comment]
This turned out to be an issue caused by Github's zip download being out of date (perhaps Github issue?).
