### ISSUE TITLE
why the adapter is not been removed?

### ISSUE THREAD

**Issue by Xiaofei-git** [vsbuffalo/scythe#33]
Dear there,
I am using Scythe to remove my adapters. But, I found the adapter did not get removed after running it (I did not meet this problem before). I don't know why and I did provide adapter file to it.

Here is the screen shot before removing adapters:
<img width="1042" alt="screen shot 2017-11-06 at 5 18 02 pm" src="https://user-images.githubusercontent.com/22894969/32467233-dd0e8750-c317-11e7-8ac0-4f9d22518d77.png">
Here it is after running scythe and sickle:
<img width="1031" alt="screen shot 2017-11-06 at 5 19 30 pm" src="https://user-images.githubusercontent.com/22894969/32467247-e7973d0c-c317-11e7-8c84-5ea43daa32c0.png">

Why this trueseq adapter is still there after running scythe? I believe it is 3'-end adapter contaminants, right?
<img width="459" alt="screen shot 2017-11-06 at 5 20 58 pm" src="https://user-images.githubusercontent.com/22894969/32467256-f1bddae8-c317-11e7-8413-669b40ddae70.png">

Here is the code that I used:

scythe -a illumina_adapters_all.fa -o sc.${ARRAYFILE}_1.fq ${ARRAYFILE}_1.fq.gz

Here is the adapter file:
[illumina_adapters_all.txt](https://github.com/vsbuffalo/scythe/files/1450564/illumina_adapters_all.txt)

Thanks a lot!

**Comment by vsbuffalo** [comment]
It looks like your adapters file is not FASTA formatted. This is why it's not properly reading the adapter file and not trimming the results. I have validated this — I will add in later versions a check to ensure the adapter file is properly formatted.

**Comment by Xiaofei-git** [comment]
Here is the screenshot for my adapter [
<img width="624" alt="screen shot 2017-11-06 at 10 22 10 pm" src="https://user-images.githubusercontent.com/22894969/32475668-0b369068-c341-11e7-8384-d8b1a0701b6b.png">

The first one is just wrong copy format. I have updated it but the extension is .txt instead of .fa because it does not support .fa to upload.

Thank you so much for your quick response!

**Comment by Xiaofei-git** [comment]
If you look at the screenshot to compare the counts of adapter contaminants, you will find the count after removing is less than before. It means it read my my adapter file?

**Comment by Xiaofei-git** [comment]
I fixed the issue finally. The reason for incomplete adapter removing is that the provided adapter file is not enough to include all contaminants. I added more sequences associated with contamination in the adapter file and finally got removed all of them.
