### ISSUE TITLE
Multiple definition errors

### ISSUE THREAD

**Issue by ericminikel** [vsbuffalo/scythe#7]
I can't build Scythe; I get the following list of errors:

$ cd vsbuffalo-scythe-872a54c/
$ make build
gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99 -c src/match.c
gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99 -c src/scythe.c
gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99 -c src/util.c
gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99 -c src/prob.c
gcc -Wall -pedantic -DVERSION=0.981 -std=gnu99 -lz -lm match.o scythe.o util.o prob.o -o scythe
scythe.o: In function `gnu_dev_major':
scythe.c:(.text+0x0): multiple definition of`gnu_dev_major'
match.o:match.c:(.text+0x0): first defined here
scythe.o: In function `gnu_dev_minor':
scythe.c:(.text+0x29): multiple definition of`gnu_dev_minor'
match.o:match.c:(.text+0x29): first defined here
scythe.o: In function `gnu_dev_makedev':
scythe.c:(.text+0x46): multiple definition of`gnu_dev_makedev'
match.o:match.c:(.text+0x46): first defined here
util.o: In function `gnu_dev_major':
util.c:(.text+0x0): multiple definition of`gnu_dev_major'
match.o:match.c:(.text+0x0): first defined here
util.o: In function `gnu_dev_minor':
util.c:(.text+0x29): multiple definition of`gnu_dev_minor'
match.o:match.c:(.text+0x29): first defined here
util.o: In function `gnu_dev_makedev':
util.c:(.text+0x46): multiple definition of`gnu_dev_makedev'
match.o:match.c:(.text+0x46): first defined here
prob.o: In function `gnu_dev_major':
prob.c:(.text+0x0): multiple definition of`gnu_dev_major'
match.o:match.c:(.text+0x0): first defined here
prob.o: In function `gnu_dev_minor':
prob.c:(.text+0x29): multiple definition of`gnu_dev_minor'
match.o:match.c:(.text+0x29): first defined here
prob.o: In function `gnu_dev_makedev':
prob.c:(.text+0x46): multiple definition of`gnu_dev_makedev'
match.o:match.c:(.text+0x46): first defined here
collect2: ld returned 1 exit status
make: **\* [build] Error 1

Thanks!

**Comment by vsbuffalo** [comment]
What system architecture do you have and what compiler and which version?

**Comment by ericminikel** [comment]
```
$ uname -p -i -r -v -s -o
Linux 2.6.32-220.23.1.el6.x86_64 #1 SMP Tue Jun 12 11:20:15 EDT 2012 x86_64 x86_64 GNU/Linux
$ gcc -v
Using built-in specs.
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.4.3/configure --prefix=/source/gnu_4.4 --with-gmp=/source/gnu_4.4 --with-gmp-include=/source/gnu_4.4/include --with-gmp-lib=source/gnu_4.4/lib --with-mpfr=/source/gnu_4.4 --with-mpfr-include=/source/gnu_4.4/include --with-mpfr-lib=/source/gnu_4.4/lib --enable-languages=c,c++,fortran --enable-shared --disable-multilib
Thread model: posix
gcc version 4.4.3 (GCC) 
```

Sorry for the vagueness the first time, I'm pretty new to unix.  Thanks in advance for your help!  And thanks for writing and open sourcing this awesome software package.

**Comment by msto** [comment]
Hey Eric, I just talked to Ashok and he gave me a quick fix. Just swap out -std=gnu99 for -std=c99 in the Makefile, and it should compile successfully.

Hi Vince, Eric and I work in the same lab and this error seems to be unique to our high performance computing cluster; I've been able to successfully compile scythe on my personal laptop without any errors. We'll be talking to our sysadmin about this issue to see if we can get it resolved, but until then do you have any advice regarding our quick fix? I'd just like to be sure changing the standard gcc uses doesn't break anything major. Thanks!

Matt

**Comment by vsbuffalo** [comment]
This is a very strange issue — I can't reproduce it, even on Linux machines. Compiling with c99 should be find though. Please re-open an issue if it doesn't work. Also, you may wish to try the experimental branch which changes the matching algorithm to search for a adapter more thoroughly in the read. Apologies for the delayed response!
